# Generated by Django 5.0.6 on 2024-12-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_place_google_place_id_alter_place_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='site_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
