# Generated by Django 5.0.6 on 2024-12-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_place_site_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
